### PR TITLE
fix: ut unstable of zk lock

### LINKED ISSUE #682: fix unstable ut; 修复不稳定的单测
**What would you like to be added**:
The UT in `components/lock/zookeeper/zookeeper_lock_test.go` is not stable. Sometimes some lines of `components/lock/zookeeper/zookeeper_lock.go` are not covered in the UT and will lead to decreased test coverage.
For example , codecov reports it in https://github.com/mosn/layotto/pull/678#issuecomment-1168279135 
image

It's because some code runs in a seperated goroutine. At the end of the test, the goroutine has not been executed:
image

We should make the test coverage stable

**Why is this needed**:
No more codecov warning

### PR DESCRIPTION
**Pull request by ZLBer**
**What this PR does**:
fix ut unstable of zookeeper lock, wait connection to close. 
**Which issue(s) this PR fixes**:

Fixes #682 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: components/lock/zookeeper/zookeeper_lock_test.go [hunk 1]
```diff
@@ -183,4 +191,7 @@ func TestZookeeperLock_ALock_BLock_AUnlock_BLock_BUnlock(t *testing.T) {
 	})
 	assert.NoError(t, err)
 	assert.Equal(t, lock.SUCCESS, unlock.Status)
+
+	//wait for connection close
+	time.Sleep(time.Second * expireTime)
```
Comment (seeflood) [inline components/lock/zookeeper/zookeeper_lock_test.go:196]: It's still unstable if we depend on time. I prefer to mock the goroutine . I submitted a PR to your branch https://github.com/ZLBer/layotto/pull/5
Please review it

**Review by seeflood — CHANGES_REQUESTED** [review]

**Review by seeflood — APPROVED** [review]
lgtm

**Review by zhenjunMa — APPROVED** [review]
