### PR TITLE
fix: GetNextId in ZK component throw zk: node does not exist

### LINKED ISSUE #747: `GetNextId` in ZK component throw `zk: node does not exist`
**What happened**:

when I call `GetNextId` API in layotto that use zookeeper as its component, I got an error, `zk: node does not exist`, as below:

image

**What you expected to happen**:

Get a unique ID

**How to reproduce it (as minimally and precisely as possible)**:

1. start a zookeeper server, maybe use docker
2. start layotto server, maybe execute this command: `./layotto start -c configs/config_zookeeper.json`
3. start a client to call `GetNextId`, maybe as follows:
```
cli, err := client.NewClientWithAddress("127.0.0.1:34904")
resp, err := cli.GetNextId(ctx, &runtimev1pb.GetNextIdRequest{
	StoreName: "sequencer_demo",
	Key:       sequencerKey,
})
```

**Anything else we need to know?**:

image

solution A:
we can add a method `createOrUpdate` to implement the logic that create a zk node when it doesn't exist or update it directly.

solution B:
add a method `isExist` to check if the request node has been created

### PR DESCRIPTION
**Pull request by bxiiiiii**
**What this PR does**:
fix GetNextId in ZK component throw zk: node does not exist
**Which issue(s) this PR fixes**:

Fixes #747 

**Special notes for your reviewer**:
Determine whether the node exists before set, and create it if it does not exist

### CODE REVIEW

File: components/sequencer/zookeeper/zookeeper_sequencer.go [hunk 1]
```diff
@@ -95,6 +95,13 @@ func (s *ZookeeperSequencer) GetNextId(req *sequencer.GetNextIdRequest) (*sequen
 	stat, err := s.client.Set("/"+req.Key, []byte(""), -1)
 
 	if err != nil {
+		if err == zk.ErrNoNode {
+			_, err1 := s.client.Create("/"+req.Key, []byte(""), zk.FlagEphemeral, zk.WorldACL(zk.PermAll))
```
Comment (ZLBer) [inline components/sequencer/zookeeper/zookeeper_sequencer.go:99]: rename  `err1`

**Review by ZLBer — APPROVED** [review]

**Review by seeflood — APPROVED** [review]
lgtm. Thanks!
